export default function ImpressumPage() {
  return (
    <div className="container mx-auto px-4 max-w-3xl py-10">
      <h1 className="text-2xl font-bold mb-6">Impressum / Legal Notice</h1>

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold mt-8 mb-3">Website Operator</h2>
          <p>
            Robert Lauko<br />
            c/o F2BII E-Commerce#660<br />
            Hintergoldingerstrasse 30<br />
            8638 Goldingen<br />
            Switzerland
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-8 mb-3">Contact</h2>
          <p>
            Email: <a href="mailto:robert@kurate.org" className="text-accent hover:underline">robert@kurate.org</a>
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-8 mb-3">Disclaimer</h2>

          <h3 className="font-medium mt-4 mb-2">Content Liability</h3>
          <p>
            The content of this website has been created with the greatest possible care. However, we cannot
            guarantee the accuracy, completeness, or timeliness of the content. As a service provider, we are
            responsible for our own content on these pages under general law. However, we are not obligated
            to monitor transmitted or stored third-party information or to investigate circumstances that
            indicate illegal activity.
          </p>

          <h3 className="font-medium mt-4 mb-2">AI-Generated Rankings</h3>
          <p>
            The paper rankings displayed on Kurate.org are generated by artificial intelligence systems
            (large language models) through automated pairwise comparison tournaments. These rankings
            reflect AI-estimated scientific impact and do not constitute peer review, editorial judgment,
            or endorsement by human experts. Rankings should not be used as the sole basis for academic
            evaluation, hiring, or funding decisions.
          </p>

          <h3 className="font-medium mt-4 mb-2">External Links</h3>
          <p>
            This website contains links to external websites (e.g., arXiv, OpenReview) over which we have
            no control. We therefore cannot accept any liability for their content. The respective provider
            or operator is always responsible for the content of linked pages.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-8 mb-3">Copyright</h2>
          <p>
            The content and works created by the website operator on these pages are subject to Swiss copyright law.
            Paper metadata (titles, authors, abstracts) is sourced from public preprint servers and used in
            accordance with their respective terms of service. AI-generated summaries and impact assessments
            are produced by our system and may be freely referenced with attribution to Kurate.org.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-8 mb-3">Applicable Law and Jurisdiction</h2>
          <p>
            Swiss law applies. The place of jurisdiction is Goldingen, Canton of St. Gallen, Switzerland,
            unless mandatory legal provisions designate a different place of jurisdiction.
          </p>
        </section>
      </div>
    </div>
  );
}
