#!/usr/bin/env python3
"""
Single-item accept/reject accuracy test — Opus 4.6 Thinking on ICLR 2025.

Methodology aligned with ReviewerToo (arXiv:2510.08867):
- 5-way categorical decision: Accept (Oral), Accept (Spotlight), Accept (Poster), Reject, Desk Reject
- Binary collapse: Accept = Oral|Spotlight|Poster, Reject = Reject|Withdrawn(→Reject)|Desk Reject
- Prompt grounded in official ICLR 2025 Reviewer Guide criteria
- Input: abstract + existing Opus 4.6 summary (rich proxy for full manuscript)
- Model: Claude Opus 4.6 with extended thinking (budget_tokens=8000)
"""
import asyncio
import json
import os
import sys
import time
import uuid
import random
import statistics
import litellm
from collections import Counter, defaultdict
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv("/app/backend/.env")
sys.path.insert(0, "/app/backend")
from emergentintegrations.llm.utils import get_integration_proxy_url

EMERGENT_LLM_KEY = os.environ.get("EMERGENT_LLM_KEY")
MONGO_URL = os.environ.get("MONGO_URL", "mongodb://localhost:27017")

PROVIDER = "anthropic"
MODEL = "claude-opus-4-6"
THINKING_PARAMS = {"extra_body": {"thinking": {"type": "enabled", "budget_tokens": 8000}}}
PARALLEL = 5

# ── Prompt grounded in ICLR 2025 Reviewer Guide ──────────────────────────────
SYSTEM_PROMPT = """You are an experienced ICLR program committee reviewer. You follow the official ICLR 2025 Reviewer Guide. Your task is to evaluate a submission and produce a structured review with a categorical decision.

When reviewing, answer these four key questions (from the ICLR 2025 Reviewer Guide):
1. What is the specific question and/or problem tackled by the paper?
2. Is the approach well motivated, including being well-placed in the literature?
3. Does the paper support the claims? (Are results—theoretical or empirical—correct and scientifically rigorous?)
4. What is the significance of the work? Does it contribute new knowledge and sufficient value to the ICLR community?

Evaluate along these axes:
- Novelty: Does it present genuinely new ideas, methods, or findings?
- Soundness: Are the theoretical claims and proofs correct? Is the methodology rigorous?
- Experimental validity: Are experiments well-designed, reproducible, with proper baselines and ablations?
- Clarity & presentation: Is the paper well-written, well-organized, and clear?
- Significance & impact: Does it advance the field meaningfully?

You must produce a categorical recommendation from exactly one of:
- Accept (Oral): Exceptional contribution, top ~2% of submissions
- Accept (Spotlight): Strong contribution, top ~5% of submissions
- Accept (Poster): Solid contribution meeting the acceptance bar, top ~30%
- Reject: Does not meet the acceptance bar
- Desk Reject: Violates submission guidelines, is incomplete, or clearly below threshold"""

USER_PROMPT = """Please review the following ICLR 2025 submission.

=== TITLE ===
{title}

=== ABSTRACT ===
{abstract}

=== AI-GENERATED RESEARCH IMPACT SUMMARY ===
(This summary was generated by analyzing the full paper text.)
{summary}

=== KEYWORDS ===
{keywords}

Produce your review in EXACTLY this JSON format (no other text outside the JSON):
{{
  "summary": "<1-2 sentence summary of the paper's contribution>",
  "strengths": ["<strength 1>", "<strength 2>"],
  "weaknesses": ["<weakness 1>", "<weakness 2>"],
  "novelty": <1-10>,
  "soundness": <1-10>,
  "experimental_validity": <1-10>,
  "clarity": <1-10>,
  "significance": <1-10>,
  "overall_score": <1-10>,
  "decision": "<one of: Accept (Oral), Accept (Spotlight), Accept (Poster), Reject, Desk Reject>",
  "confidence": <1-5>,
  "justification": "<2-3 sentence justification for your decision>"
}}"""


async def sample_papers():
    """Sample 50 accept + 50 reject from ICLR 2025, following ReviewerToo methodology."""
    from motor.motor_asyncio import AsyncIOMotorClient
    client = AsyncIOMotorClient(MONGO_URL)
    db = client["test_database"]

    iclr_ds = [d for d in await db.validation_papers.distinct("dataset_id") if "iclr" in d]

    accepts, rejects = [], []
    for ds in iclr_ds:
        async for p in db.validation_papers.find(
            {"dataset_id": ds, "year": 2025},
            {"_id": 0, "id": 1, "title": 1, "abstract": 1, "decision": 1,
             "h1_avg_rating": 1, "scores": 1, "dataset_id": 1, "keywords": 1,
             "ai_impact_summary_opus46": 1, "single_item_score": 1,
             "label": 1},
        ):
            d = p.get("decision", "")
            if d in ("Oral", "Spotlight", "Poster"):
                p["binary_label"] = "accept"
                accepts.append(p)
            elif d in ("Reject", "Withdrawn", "Desk Rejected"):
                # Paper methodology: Withdrawn → Reject, Desk Reject kept separate
                p["binary_label"] = "reject"
                rejects.append(p)

    random.seed(42)
    random.shuffle(accepts)
    random.shuffle(rejects)

    sample = accepts[:50] + rejects[:50]
    print(f"Pool: {len(accepts)} accepts, {len(rejects)} rejects (ICLR 2025)")
    print(f"Sample: 50 accepts, 50 rejects")

    accept_tiers = Counter(p["decision"] for p in accepts[:50])
    reject_tiers = Counter(p["decision"] for p in rejects[:50])
    print(f"  Accept tiers: {dict(accept_tiers)}")
    print(f"  Reject tiers: {dict(reject_tiers)}")

    client.close()
    return sample


def build_litellm_params(system_msg, user_msg):
    """Build litellm.completion params matching the codebase pattern (llm.py:830-847)."""
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_msg},
    ]
    params = {
        "model": f"{PROVIDER}/{MODEL}",
        "messages": messages,
        "api_key": EMERGENT_LLM_KEY,
    }
    is_emergent = EMERGENT_LLM_KEY and EMERGENT_LLM_KEY.startswith("sk-emergent")
    if is_emergent:
        proxy_url = get_integration_proxy_url()
        params["api_base"] = proxy_url + "/llm"
        params["custom_llm_provider"] = "openai"
        params["model"] = MODEL  # strip provider prefix for emergent proxy
    params.update(THINKING_PARAMS)
    return params


async def predict_single(paper, sem, idx, total):
    """Ask Opus 4.6 Thinking for a structured review + categorical decision."""
    async with sem:
        abstract = paper.get("abstract", "")
        summary = paper.get("ai_impact_summary_opus46", "")
        title = paper.get("title", "Untitled")
        keywords = ", ".join(paper.get("keywords", []))

        if not abstract:
            return {**paper, "ai_decision": None, "error": "no abstract"}

        prompt = USER_PROMPT.format(
            title=title, abstract=abstract,
            summary=summary or "(no summary available)",
            keywords=keywords or "(none)",
        )
        params = build_litellm_params(SYSTEM_PROMPT, prompt)

        try:
            loop = asyncio.get_event_loop()
            raw_response = await loop.run_in_executor(
                None, lambda: litellm.completion(**params),
            )
            text = raw_response.choices[0].message.content if raw_response.choices else ""
            text = text.strip()

            # Extract JSON from possible markdown wrapping
            if "```" in text:
                parts = text.split("```")
                for part in parts[1:]:
                    cleaned = part.strip()
                    if cleaned.startswith("json"):
                        cleaned = cleaned[4:].strip()
                    if cleaned.startswith("{"):
                        text = cleaned
                        break

            result = json.loads(text)

            # Extract categorical decision
            ai_decision_raw = result.get("decision", "")
            # Map to binary
            if any(x in ai_decision_raw for x in ["Oral", "Spotlight", "Poster"]):
                ai_binary = "accept"
            else:
                ai_binary = "reject"

            # Token usage
            usage = raw_response.usage
            tokens = {
                "input": getattr(usage, "prompt_tokens", 0),
                "output": getattr(usage, "completion_tokens", 0),
            }
            details = getattr(usage, "completion_tokens_details", None)
            if details:
                tokens["thinking"] = getattr(details, "reasoning_tokens", 0) or 0

            print(f"  [{idx+1}/{total}] {title[:50]}... → {ai_decision_raw} (actual: {paper['decision']}) {'✓' if ai_binary == paper['binary_label'] else '✗'}")

            return {
                **paper,
                "ai_decision_raw": ai_decision_raw,
                "ai_decision": ai_binary,
                "ai_review": result,
                "ai_overall_score": result.get("overall_score"),
                "ai_confidence": result.get("confidence"),
                "tokens": tokens,
                "error": None,
            }
        except json.JSONDecodeError as e:
            print(f"  [{idx+1}/{total}] JSON parse error: {e}")
            return {**paper, "ai_decision": None, "error": f"JSON parse: {e}"}
        except Exception as e:
            print(f"  [{idx+1}/{total}] Error: {e}")
            return {**paper, "ai_decision": None, "error": str(e)}


def compute_metrics(results, label=""):
    """Compute accuracy, precision, recall, F1, confusion matrix."""
    tp = fp = tn = fn = 0
    for r in results:
        pred = r["ai_decision"]
        actual = r["binary_label"]
        if pred == "accept" and actual == "accept":   tp += 1
        elif pred == "accept" and actual == "reject":  fp += 1
        elif pred == "reject" and actual == "reject":  tn += 1
        elif pred == "reject" and actual == "accept":  fn += 1

    total = tp + fp + tn + fn
    accuracy  = (tp + tn) / total if total else 0
    precision = tp / (tp + fp) if (tp + fp) else 0
    recall    = tp / (tp + fn) if (tp + fn) else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0

    print(f"\n  {label}")
    print(f"  Accuracy:  {accuracy:.1%} ({tp + tn}/{total})")
    print(f"  Precision: {precision:.1%}  (of predicted accepts, how many are truly accepted)")
    print(f"  Recall:    {recall:.1%}  (of truly accepted, how many did we catch)")
    print(f"  F1:        {f1:.3f}")
    print(f"  Confusion: TP={tp} FP={fp} FN={fn} TN={tn}")

    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1,
            "tp": tp, "fp": fp, "fn": fn, "tn": tn, "total": total}


def compute_human_baseline(papers):
    """Human baseline: threshold on avg reviewer score → binary accept/reject."""
    with_scores = [p for p in papers if p.get("h1_avg_rating") is not None]
    if not with_scores:
        return None

    best_acc, best_thresh = 0, 0
    for thresh in [x * 0.1 for x in range(30, 80)]:
        correct = sum(1 for p in with_scores
                      if ("accept" if p["h1_avg_rating"] >= thresh else "reject") == p["binary_label"])
        acc = correct / len(with_scores)
        if acc > best_acc:
            best_acc, best_thresh = acc, thresh

    # Build result list for compute_metrics
    for p in with_scores:
        p["ai_decision"] = "accept" if p["h1_avg_rating"] >= best_thresh else "reject"

    print(f"\n{'='*70}")
    print(f"HUMAN BASELINE (avg reviewer score, threshold={best_thresh:.1f})")
    print(f"{'='*70}")
    metrics = compute_metrics(with_scores, f"Human (threshold={best_thresh:.1f})")
    metrics["threshold"] = best_thresh

    # Clean up temporary field
    for p in with_scores:
        del p["ai_decision"]

    return metrics


def compute_5way_accuracy(results):
    """5-way accuracy: how often does AI match the exact ICLR decision tier?"""
    # Normalize decisions
    TIER_MAP = {
        "Accept (Oral)": "Oral", "Accept (Spotlight)": "Spotlight",
        "Accept (Poster)": "Poster", "Reject": "Reject", "Desk Reject": "Desk Rejected",
    }

    correct = 0
    total = 0
    confusion = defaultdict(lambda: defaultdict(int))

    for r in results:
        actual = r.get("decision", "")
        # Map Withdrawn → Reject for 5-way
        if actual == "Withdrawn":
            actual = "Reject"
        predicted_raw = r.get("ai_decision_raw", "")
        predicted = TIER_MAP.get(predicted_raw, predicted_raw)

        confusion[actual][predicted] += 1
        total += 1
        if actual == predicted:
            correct += 1

    print(f"\n  5-Way Accuracy: {correct}/{total} = {correct/total:.1%}")
    print(f"\n  5-Way Confusion Matrix (rows=actual, cols=predicted):")
    all_tiers = ["Oral", "Spotlight", "Poster", "Reject", "Desk Rejected"]
    header = f"  {'Actual':<15}" + "".join(f"{t:<15}" for t in all_tiers)
    print(header)
    for actual in all_tiers:
        row = f"  {actual:<15}"
        for pred in all_tiers:
            count = confusion[actual].get(pred, 0)
            row += f"{count:<15}"
        print(row)

    return {"accuracy_5way": correct / total if total else 0, "confusion": dict(confusion)}


async def main():
    print("=" * 70)
    print("OPUS 4.6 THINKING — Single-Item Accept/Reject Accuracy")
    print(f"Following ReviewerToo (arXiv:2510.08867) methodology")
    print(f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print("=" * 70)

    # 1. Sample papers
    papers = await sample_papers()

    # 2. Human baseline
    human_metrics = compute_human_baseline(papers)

    # 3. Run Opus 4.6 Thinking predictions
    print(f"\n{'='*70}")
    print(f"OPUS 4.6 THINKING PREDICTIONS (n={len(papers)}, parallel={PARALLEL})")
    print(f"Input: abstract + Opus 4.6 summary | Thinking: budget_tokens=8000")
    print(f"{'='*70}\n")

    sem = asyncio.Semaphore(PARALLEL)
    start = time.time()

    tasks = [predict_single(p, sem, i, len(papers)) for i, p in enumerate(papers)]
    results = await asyncio.gather(*tasks)

    elapsed = time.time() - start

    successes = [r for r in results if not isinstance(r, Exception) and r.get("ai_decision")]
    failures  = [r for r in results if isinstance(r, Exception) or not r.get("ai_decision")]

    print(f"\nCompleted in {elapsed:.0f}s | Successes: {len(successes)} | Failures: {len(failures)}")
    if failures:
        errs = [f.get("error", str(f)) if isinstance(f, dict) else str(f) for f in failures[:3]]
        print(f"  Sample errors: {errs}")

    # Total tokens
    total_input = sum(r.get("tokens", {}).get("input", 0) for r in successes)
    total_output = sum(r.get("tokens", {}).get("output", 0) for r in successes)
    total_thinking = sum(r.get("tokens", {}).get("thinking", 0) for r in successes)
    print(f"  Tokens: input={total_input:,} output={total_output:,} thinking={total_thinking:,}")

    if not successes:
        print("No successful predictions. Aborting.")
        return

    # 4. Binary accuracy
    print(f"\n{'='*70}")
    print("BINARY ACCEPT/REJECT RESULTS")
    print(f"{'='*70}")
    ai_metrics = compute_metrics(successes, "Opus 4.6 Thinking (direct review)")

    # 5. 5-way accuracy
    print(f"\n{'='*70}")
    print("5-WAY CATEGORICAL RESULTS")
    print(f"{'='*70}")
    five_way = compute_5way_accuracy(successes)

    # 6. Per-tier accuracy
    print(f"\n  Per-tier binary accuracy:")
    for tier in ["Oral", "Spotlight", "Poster", "Reject", "Withdrawn", "Desk Rejected"]:
        tier_results = [r for r in successes if r.get("decision") == tier]
        if tier_results:
            correct = sum(1 for r in tier_results if r["ai_decision"] == r["binary_label"])
            print(f"    {tier:<15}: {correct}/{len(tier_results)} = {correct/len(tier_results):.1%}")

    # 7. AI score distribution
    print(f"\n  AI overall_score distribution by actual decision:")
    for tier in ["Oral", "Spotlight", "Poster", "Reject", "Withdrawn"]:
        scores = [r["ai_overall_score"] for r in successes
                  if r.get("decision") == tier and r.get("ai_overall_score")]
        if scores:
            print(f"    {tier:<15}: mean={statistics.mean(scores):.1f} median={statistics.median(scores)} range=[{min(scores)}, {max(scores)}]")

    # 8. Confidence calibration
    correct_conf = [r.get("ai_confidence", 3) for r in successes if r["ai_decision"] == r["binary_label"]]
    wrong_conf   = [r.get("ai_confidence", 3) for r in successes if r["ai_decision"] != r["binary_label"]]
    if correct_conf:
        print(f"\n  Confidence (correct): mean={statistics.mean(correct_conf):.1f}")
    if wrong_conf:
        print(f"  Confidence (wrong):   mean={statistics.mean(wrong_conf):.1f}")

    # 9. Summary comparison
    print(f"\n\n{'='*70}")
    print("SUMMARY COMPARISON (binary accept/reject)")
    print(f"{'='*70}")
    print(f"{'Method':<45} {'Acc':>7} {'Prec':>7} {'Recall':>7} {'F1':>7}")
    print(f"{'-'*73}")

    # Paper benchmarks
    print(f"{'ReviewerToo META (all) [paper]':<45} {'81.8%':>7} {'—':>7} {'—':>7} {'—':>7}")
    print(f"{'Human avg [paper]':<45} {'83.9%':>7} {'—':>7} {'—':>7} {'—':>7}")
    print(f"{'Human top-1% [paper]':<45} {'92.4%':>7} {'—':>7} {'—':>7} {'—':>7}")
    print(f"{'-'*73}")

    # Our results
    if human_metrics:
        h = human_metrics
        t = h['threshold']
        print(f"{'Human reviewers (our data, thresh='+str(t)+')':<45} {h['accuracy']:>6.1%} {h['precision']:>6.1%} {h['recall']:>6.1%} {h['f1']:>6.3f}")

    a = ai_metrics
    print(f"{'Opus 4.6 Thinking (abstract+summary)':<45} {a['accuracy']:>6.1%} {a['precision']:>6.1%} {a['recall']:>6.1%} {a['f1']:>6.3f}")

    # 10. Save detailed results
    report = {
        "date": datetime.now(timezone.utc).isoformat(),
        "methodology": {
            "source": "ReviewerToo (arXiv:2510.08867)",
            "model": "claude-opus-4-6 (thinking, budget_tokens=8000)",
            "input": "abstract + opus46_summary",
            "prompt": "ICLR 2025 Reviewer Guide criteria",
            "sample": "50 accept + 50 reject, ICLR 2025, seed=42",
            "categories": "Oral/Spotlight/Poster/Reject/Desk Reject (Withdrawn→Reject)",
        },
        "sample_composition": {
            "accept_tiers": dict(Counter(r["decision"] for r in successes if r["binary_label"] == "accept")),
            "reject_tiers": dict(Counter(r["decision"] for r in successes if r["binary_label"] == "reject")),
        },
        "binary_metrics": ai_metrics,
        "five_way_metrics": five_way,
        "human_baseline": human_metrics,
        "paper_benchmarks": {
            "reviewertoo_meta": 0.818,
            "human_avg": 0.839,
            "human_top1pct": 0.924,
        },
        "tokens": {
            "total_input": total_input,
            "total_output": total_output,
            "total_thinking": total_thinking,
        },
        "elapsed_seconds": elapsed,
        "detailed_results": [
            {
                "id": r["id"],
                "title": r.get("title", ""),
                "dataset": r.get("dataset_id", ""),
                "topic": r.get("label", ""),
                "decision_actual": r.get("decision"),
                "binary_actual": r["binary_label"],
                "decision_predicted": r.get("ai_decision_raw"),
                "binary_predicted": r["ai_decision"],
                "correct_binary": r["ai_decision"] == r["binary_label"],
                "correct_5way": r.get("ai_decision_raw", "").replace("Accept (", "").replace(")", "") == (r.get("decision") if r.get("decision") != "Withdrawn" else "Reject"),
                "overall_score": r.get("ai_overall_score"),
                "confidence": r.get("ai_confidence"),
                "h1_avg_rating": r.get("h1_avg_rating"),
                "review": r.get("ai_review", {}),
            }
            for r in successes
        ],
    }

    report_path = "/app/tools/opus46_accept_reject_results.json"
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    print(f"\nDetailed results saved to {report_path}")


if __name__ == "__main__":
    asyncio.run(main())
